name: drive_sync
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  path_provider: ^2.1.3
  path: ^1.9.0
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  workmanager: ^0.9.0
  file_picker: ^10.3.3
  http: ^1.2.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
